services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: postgres
    volumes:
      - dati_postgres:/var/lib/postgresql/data # Salva i dati anche se spegni tutto
      - ./init-db:/docker-entrypoint-initdb.d

  web:
    build: .             # Costruisce l'immagine usando il Dockerfile sopra
    ports:
      - "5000:5000"      # Flask di solito gira sulla 5000
    volumes:
      - .:/app           # Sincronizza il codice (auto-aggiornamento)
    environment:
      - DATABASE_URL=postgresql://postgres:jIkyt0SYok5UpWgy@db.dtjxphfwyxegadujegwv.supabase.co:5432/postgres
    depends_on:
      - db               # Avvia prima il database, poi Flask

volumes:
  dati_postgres:         # Crea uno spazio su disco per il database